// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Full In-Memory Storage polyfill for environments where localStorage throws (Safari Private mode/restricted cookies)
class InMemoryStorage {
  private data: Record<string, string> = {};
  get length() { return Object.keys(this.data).length; }
  getItem(key: string) { return this.data[key] || null; }
  setItem(key: string, value: string) { this.data[key] = value; }
  removeItem(key: string) { delete this.data[key]; }
  clear() { this.data = {}; }
  key(index: number) { return Object.keys(this.data)[index] || null; }
}

const getSafeStorage = () => {
  try {
    const testKey = '__storage_test__';
    window.localStorage.setItem(testKey, testKey);
    window.localStorage.removeItem(testKey);
    return window.localStorage;
  } catch (e) {
    console.warn('[STORAGE] LocalStorage is inaccessible, using InMemoryStorage');
    return new InMemoryStorage();
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: getSafeStorage() as any,
    persistSession: true,
    autoRefreshToken: true,
  },
  db: {
    schema: 'public'
  },
  global: {
    headers: {
      'x-connection-pool-size': '20'
    }
  }
});